WIP Add react testing library
USSBA/sba-gov-break-even-calculator pull request #110
Opened 2020-12-14 21:47 UTC by kscoulter

2020-12-15 23:32 UTC, peggles2 requested changes
Can you add a description for this pull request? 
Just a few comments.

2020-12-16 16:24 UTC, peggles2 commented on solution/ui/src/pages/index.test.js
> +// import { shallow } from 'enzyme'
We can remove this comment as well

2020-12-16 17:35 UTC, peggles2 requested changes
Just one more tweak :)

2020-12-16 17:35 UTC, peggles2 commented on solution/ui/src/pages/index.test.js
>  import { shallow } from 'enzyme'
Are we using enzyme anymore here?

2020-12-16 17:45 UTC, kscoulter commented on solution/ui/src/pages/index.test.js
>  import { shallow } from 'enzyme'
yes, acceptance criteria for this ticket is one passing test. I didn't rewrite them all for this part.

2020-12-16 18:46 UTC, peggles2 approved these changes
Nice work!

2020-12-16 18:48 UTC, merged