Feature/bep graph tests
USSBA/sba-gov-break-even-calculator pull request #111
Opened 2020-12-18 14:57 UTC by peggles2

This pull request updates Break Even Point Graph tests to use React Testing Library. Also added some more tests.

2020-12-18 16:43 UTC, kscoulter requested changes
Great start! Just a few changes - mostly adding even more tests for the interactive part of the graph.

2020-12-18 16:43 UTC, kscoulter commented on solution/ui/src/components/molecules/breakEvenGraph/breakEvenGraph.test.js
> +import { Results } from '../../organisms'
I would argue this test suite should live in Results, if that's the component we're mounting

2020-12-18 16:43 UTC, kscoulter commented on solution/ui/src/components/molecules/breakEvenGraph/breakEvenGraph.test.js
> +  beforeEach(() => {
that's a great shortcut!

2020-12-18 16:43 UTC, kscoulter commented on solution/ui/src/components/molecules/breakEvenGraph/breakEvenGraph.test.js
> +    screen.getByTestId('graph')
you don't need an expect here? Might want to consult on the style guide for tests. Not sure which one is more readable.

2020-12-18 16:43 UTC, kscoulter commented on solution/ui/src/components/molecules/breakEvenGraph/breakEvenGraph.test.js
> +    screen.getByRole("img", { name: /unit sales label/i });
passing an option to get is a great idea

2020-12-18 16:43 UTC, kscoulter commented on solution/ui/src/components/molecules/breakEvenGraph/breakEvenGraph.test.js
>    })
You should add tests for interactions. The hiding and showing of tooltips and such.

2020-12-18 16:44 UTC, peggles2 commented on solution/ui/src/components/molecules/breakEvenGraph/breakEvenGraph.test.js
> +import { Results } from '../../organisms'
We are testing the graph pieces. If we do that we would then have a huge test here.

2020-12-18 18:52 UTC, peggles2 commented on solution/ui/src/components/molecules/breakEvenGraph/breakEvenGraph.test.js
>    })
Acceptance criteria was to just convert the existing tests. I added a few more too but this will be out of scope of this ticket.

2020-12-18 18:56 UTC, peggles2 commented on solution/ui/src/components/molecules/breakEvenGraph/breakEvenGraph.test.js
> +    screen.getByTestId('graph')
its just checking that its rendered.

2020-12-22 18:32 UTC, chris-poe commented on solution/ui/src/components/molecules/breakEvenResultsCard/breakEvenResultsCard.js
> +                  <Card.Description extra='true'>
Was it determined that this needed to be explicitly passed `true` and just passing `extra` as a prop was not enough?

2020-12-22 18:32 UTC, chris-poe approved these changes

2020-12-22 20:12 UTC, kscoulter approved these changes

2020-12-23 13:29 UTC, merged