WIP TC-632 Add React Testing Library to atoms
USSBA/sba-gov-break-even-calculator pull request #112
Opened 2020-12-18 16:53 UTC by kscoulter

2020-12-18 19:37 UTC, peggles2 requested changes
Looks good nice job with the user interaction tests. Lets discuss later about how/if we want to restructure the tests. Let's keep it the way it is for now.

2020-12-18 19:37 UTC, peggles2 commented on solution/ui/package.json
> +    "@testing-library/user-event": "^12.6.0",
master merged with this? I think master already has this stuff

2020-12-18 19:37 UTC, peggles2 commented on solution/ui/src/__mocks__/gatsby.js
> +}
Nice job with the mocks!!

2020-12-18 19:37 UTC, peggles2 commented on solution/ui/src/components/atoms/editableTotal/editableTotal.test.js
> +    render(<EditableTotal {...sampleProps}/>)
These are rendered again over and over. Might be better to put this in a beforeEach

2020-12-18 19:37 UTC, peggles2 commented on solution/ui/src/components/molecules/breakEvenProfileCard/breakEvenProfileCard.test.js
> +  })
Nice job with the interaction tests

2020-12-18 19:37 UTC, peggles2 commented on solution/ui/src/pages/index.test.js
> +})
For now lets keep the tests we had in the same structure and later lets think if we want to re-organize it.

2020-12-22 18:35 UTC, chris-poe commented on solution/ui/src/components/atoms/editableTotal/editableTotal.test.js
> +    render(<EditableTotal {...sampleProps}/>)
Is this considered resolved?

2020-12-22 20:12 UTC, kscoulter commented on solution/ui/src/components/atoms/editableTotal/editableTotal.test.js
> +    render(<EditableTotal {...sampleProps}/>)
yes

2020-12-22 20:14 UTC, chris-poe approved these changes

2020-12-22 20:14 UTC, merged