Feature/rtl fixed costs
USSBA/sba-gov-break-even-calculator pull request #130
Opened 2021-01-15 21:39 UTC by peggles2

This pull request adds React Testing Library for fixed costs.

2021-01-15 22:18 UTC, kscoulter requested changes

2021-01-15 22:18 UTC, kscoulter commented on solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
> +  test('Has a heading caleld "Calculate your total fixed costs"', () => {
spelling mistake

2021-01-15 22:18 UTC, kscoulter commented on solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
> +    expect(screen.queryByRole('spinbutton', { name: /other fixed costs/i })).not.toBeInTheDocument()
you can put a test id on the whole form and assert that it's not showing up, instead of testing for each input field to be hidden.

2021-01-15 22:18 UTC, kscoulter commented on solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
> +  test('shows the continue button when a selection has been made', () => {
good one

2021-01-15 22:18 UTC, kscoulter commented on solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
> +    expect(screen.queryByRole('spinbutton', { name: /total fixed cost/i })).not.toBeInTheDocument()
same comment here, put test id on the form and assert that the whole form is not present.

2021-01-15 22:24 UTC, peggles2 commented on solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
> +    expect(screen.queryByRole('spinbutton', { name: /other fixed costs/i })).not.toBeInTheDocument()
This is a more detailed test. It also is testing none of these show up. The other way around is more generalized.

2021-01-19 16:33 UTC, kscoulter approved these changes

2021-01-19 17:01 UTC, merged