TC-692 - RTL tests for unitSales
USSBA/sba-gov-break-even-calculator pull request #138
Opened 2021-01-25 22:32 UTC by peggles2

This pull request, writes React Testing Library tests for the break even point calculator

2021-01-26 15:55 UTC, kscoulter requested changes

2021-01-26 15:55 UTC, kscoulter commented on solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
> +    expect(screen.getByRole('spinbutton', {  name: /total fixed cost/i})).toHaveValue(null)
This doesn't check the fields being reset. It checks visibility.

2021-01-26 15:55 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
>      jest.clearAllMocks()
I don't think you needs this for RTL, this is done automatically

2021-01-26 15:55 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    screen.getByRole('button', {  name: /continue/i})
spacing is off

2021-01-26 15:55 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    userEvent.type(screen.getByRole('spinbutton', {  name: /number of units to sell\*/i}), '123')
squiggly bracket spacing is off

2021-01-26 15:55 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +  test('calls setNumUnits on Change', () => {
Rename this, were' not testing that a function is being called anymore

2021-01-26 15:55 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    userEvent.type(screen.getByRole('spinbutton', {  name: /number of units to sell\*/i}), '')
Is this line needed? Should it not be empty by default at the start?

2021-01-26 15:55 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    screen.getByRole('spinbutton', {  name: /number of units to sell\*/i})
I would check that the correct heading is present and the next page heading is absent

2021-01-26 15:55 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    userEvent.type(screen.getByRole('spinbutton', {  name: /number of units to sell\*/i}), '')
Same as above, is this actually needed?

2021-01-26 15:55 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    userEvent.click(screen.getByRole('button', {  name: /back to price per unit/i}))
Bracket spacing is off

2021-01-26 15:55 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +  test('calls restart prop on restart analysis click', () => {
Rename this test

2021-01-26 15:55 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    expect(screen.queryByRole('spinbutton', { name: /total fixed cost/i })).not.toBeInTheDocument()
Continue button isn't in the document when you reset, let's check for that too

2021-01-26 16:12 UTC, peggles2 commented on solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
> +    expect(screen.getByRole('spinbutton', {  name: /total fixed cost/i})).toHaveValue(null)
It's converting what we had enzyme doing there. If you select no, and set the rent to 100 then change to yes your fixed cost is the initial value which is ''.  I was just following what previous test did. However with RTL you can't test state so just checked the field is null. If thats not what it did before let me know let's discuss.

2021-01-26 16:13 UTC, peggles2 commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
>      jest.clearAllMocks()
? isn't that what we did for pricePerUnit and we said we have to walk through the tests?  Let's discuss.

2021-01-26 16:18 UTC, peggles2 commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    userEvent.type(screen.getByRole('spinbutton', {  name: /number of units to sell\*/i}), '')
not really. More readable thats all. I'll take it off doesn't matter either way.

2021-01-26 16:19 UTC, peggles2 commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    screen.getByRole('spinbutton', {  name: /number of units to sell\*/i})
If it doesn't go to the next step it would see just the text field for number of units to sell. So this test is valid.

2021-01-26 19:00 UTC, kscoulter commented on solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
> +    expect(screen.getByRole('spinbutton', {  name: /total fixed cost/i})).toHaveValue(null)
It's not going to be a 1:1 conversion because their testing philosophies are different. In order to assert field reset, you need to go back the rent field and assert that it is now 0 and not 100

2021-01-26 19:01 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
>      jest.clearAllMocks()
I did not reset all mocks in pricePerUnit

2021-01-26 19:02 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    screen.getByRole('spinbutton', {  name: /number of units to sell\*/i})
what if they're both visible? this test won't catch that

2021-01-26 19:04 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +  test('Sets the number of units to 123', () => {
👍

2021-01-26 19:04 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    expect(screen.getByRole('button', { name: /continue/i }))
👍

2021-01-26 19:59 UTC, peggles2 commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
>      jest.clearAllMocks()
I was looking at beforeEach got it now.

2021-01-27 16:47 UTC, peggles2 commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    screen.getByRole('spinbutton', {  name: /number of units to sell\*/i})
if they were both visible wouldn't it pass seeing the heading too?

2021-01-27 17:05 UTC, kscoulter approved these changes

2021-01-27 17:05 UTC, kscoulter commented on solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
> +    expect(screen.getByRole('spinbutton', {  name: /rent/i})).toHaveValue(null)
adjust spacing on the bracket

2021-01-27 17:05 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    expect(screen.getByRole('heading', {  name: /estimate your expected unit sales/i})).toBeInTheDocument()
bracket spacing

2021-01-27 17:05 UTC, kscoulter commented on solution/ui/src/components/organisms/unitSales/unitSales.test.js
> +    expect(screen.queryByRole('heading', {  name: /do you know your variable cost per unit\?\*/i})).not.toBeInTheDocument()
thanks for adding this test

2021-01-27 17:15 UTC, kscoulter approved these changes

2021-01-27 17:37 UTC, merged