Feature/rtl variable costs
USSBA/sba-gov-break-even-calculator pull request #140
Opened 2021-01-29 14:42 UTC by peggles2

This pull request updates our tests to use React Testing Library for Variable Costs instead of Enzyme.

2021-01-29 19:17 UTC, kscoulter requested changes

2021-01-29 19:17 UTC, kscoulter commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +    expect(notKnowVariableCost.value).toBeNull
Check for input field and button presence here

2021-01-29 19:17 UTC, kscoulter commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  test('has correct initial fields', () => {
Rename to something more concrete.

2021-01-29 19:17 UTC, kscoulter commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  test('sets VariableCosts value to true on radio button selection', () => {
we may not need this test, it seems in conflict with RTL principles. It's not necessarily checking something a user can see. Up to you though

2021-01-29 19:17 UTC, kscoulter commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +    const knowVariableCost = screen.getByRole('radio', {
this variable is used in a bunch of tests, maybe pull it out to the top of describe block? Or put it in beforeEach?

2021-01-29 19:17 UTC, kscoulter commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  test('shows variable cost suggestion box on yes selection', () => {
what's a suggestion box?

2021-01-29 19:17 UTC, kscoulter commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  })
👍

2021-01-29 19:17 UTC, kscoulter commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  test('calculates the variable cost value and when you go to the next page it displays it', () => {
👍

2021-01-29 19:17 UTC, kscoulter commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  test('saves the variable cost value and when you go to the next page it displays it', () => {
Is this test doubled? It's named the same as a test above it

2021-01-29 19:17 UTC, kscoulter commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  it('Does not go to the next step when variable cost field is empty', () => {
👏

2021-01-29 19:17 UTC, kscoulter commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  it('resets fields on radio button switch', () => {
Very good

2021-01-29 19:17 UTC, kscoulter commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  test('displays warning message when appropriate', () => {
rename displays warning message when variable cost is higher than price per unit

2021-01-29 20:16 UTC, peggles2 commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +    expect(notKnowVariableCost.value).toBeNull
This is just checking the initial state before any radio buttons are clicked. So input fields are not displaying. That is checked in the other tests.

2021-01-29 20:18 UTC, peggles2 commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  test('sets VariableCosts value to true on radio button selection', () => {
it testes that when you click on the radio button the button is selected. Good to test in case both buttons get selected or none get selected etc.

2021-01-29 20:20 UTC, peggles2 commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  test('shows variable cost suggestion box on yes selection', () => {
![Screen Shot 2021-01-29 at 3 19 34 PM](https://user-images.githubusercontent.com/7727136/106323477-7cbda180-6245-11eb-9016-424a868f637c.png)

2021-01-29 20:23 UTC, peggles2 commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  test('shows variable cost suggestion box on yes selection', () => {
![Screen Shot 2021-01-29 at 3 23 05 PM](https://user-images.githubusercontent.com/7727136/106323768-f35a9f00-6245-11eb-924c-3bcd4e03a443.png)

2021-01-29 21:42 UTC, peggles2 commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +    const knowVariableCost = screen.getByRole('radio', {
👍  good idea

2021-01-29 21:48 UTC, peggles2 commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +  test('saves the variable cost value and when you go to the next page it displays it', () => {
One is for individual vc the other is when you know your total. I'll update the description

2021-02-01 22:29 UTC, mikewolfd requested changes
There seems to be some remaining issues, I left the appropriate comments

2021-02-01 22:29 UTC, mikewolfd commented on solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
>      screen.getByRole('heading', { name: /calculate your total fixed costs/i })
are you missing an expect statement here?

2021-02-01 22:29 UTC, mikewolfd commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +    expect(screen.getByRole('button', { name: /continue/i })).toBeInTheDocument()
this button should still be here after the previous click? or are you missing .not here?

2021-02-01 22:29 UTC, mikewolfd commented on solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
>      screen.getByRole('heading', { name: /calculate your total fixed costs/i })
are you missing an expect check here, otherwise this test is empty?

2021-02-01 22:29 UTC, mikewolfd commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +    screen.getByText(/\$17/i)
expect statement?

2021-02-01 22:29 UTC, mikewolfd commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +    expect(screen.getByText(warningMsg)).toBeInTheDocument
toBeInTheDocument()

2021-02-01 22:35 UTC, peggles2 commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +    expect(screen.getByRole('button', { name: /continue/i })).toBeInTheDocument()
either radio button selected the button should be there. It's only not there when nothing is selected.

2021-02-01 22:37 UTC, peggles2 commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +    expect(screen.getByText(warningMsg)).toBeInTheDocument
good catch!

2021-02-01 22:38 UTC, peggles2 commented on solution/ui/src/components/organisms/variableCosts/variableCosts.test.js
> +    screen.getByText(/\$17/i)
the test works anyway but I agree expect statements make it more readable so I'll update the code thanks!

2021-02-02 18:45 UTC, mikewolfd approved these changes
Looks good!

2021-02-02 19:29 UTC, merged